### PR TITLE
REL-872 | Do not process expired messages to the DLQ

### PR DESCRIPTION
**Pull request by jayceeb**
### Description

Added the option to stop processing expired messages to the DLQ. Failed messages, if any, will still be processed into the DLQ.

### CODE REVIEW

**Comment by csdcrussell** [comment]
Wait, the cookbook setting dlq_process_expired turns processing of expired messages OFF? Seems backwards. ;)

**Comment by jayceeb** [comment]
yea that does seem weird hah. I will change that

**Comment by csdcrussell** [comment]
After talking it over with @markhamstra and @davidnavas I think we are going to want a more nuanced approach then just sending DLQ directly to /dev/null.  We'd like to somehow log the fact that DLQ messages are being discarded along with some info about those messages such as which queue they originally targetted, so we may have to set up a processor for the DLQ.

I am trying to track down what our current redelivery policy is for the various queues.

**Comment by csdcrussell** [comment]
Discard messages from the DLQ after 7 days:
````
<sharedDeadLetterStrategy expiration="604800000" processExpired="true"  processNonPersistent="true" />

**Review by csdcrussell — APPROVED** [review]

**Comment by csdcrussell** [comment]
I would merge but I don't appear to have write-access.

**Comment by jayceeb** [comment]
oh weird

**Comment by csdcrussell** [comment]
How do we get this change out to various environments? You bumped the version here but do we need to update some recipes?

**Pull request merged**
